#!/bin/sh

GH_USER=Clommunity
GH_REPO=package-docker-compose
NAME=docker-compose

echo "Downloading ${GH_REPO} zip file..."
curl "https://codeload.github.com/${GH_USER}/${GH_REPO}/zip/master" > ${GH_REPO}.zip

echo "Unzipping ${GH_REPO}.zip"
unzip ${GH_REPO}.zip

echo "Installing ${GH_REPO}"
cd ${GH_REPO}-master/
make install

echo "Updating package info..."
curl -s https://api.github.com/repos/$GH_USER/$GH_REPO/git/refs/heads/master | grep 'sha'|awk -F':' '{print $2}'|awk -F'"' '{print $2}' > /etc/cloudy/${GH_USER}-${GH_REPO}.sha

echo "Cleaning up..."
cd ..
rm -rf ${GH_REPO}-master ${GH_REPO}.zip

echo "Done."
