#!/bin/sh

GH_USER=Clommunity
GH_REPO=package-docker-compose
NAME=docker-compose

curl "https://codeload.github.com/${GH_USER}/${GH_REPO}/zip/master" > ${GH_REPO}.zip
unzip ${GH_REPO}.zip 
cd ${GH_REPO}-master/

# Update info
mkdir -p /etc/cloudy
curl -s https://api.github.com/repos/$GH_USER/$GH_REPO/git/refs/heads/master | grep 'sha'|awk -F':' '{print $2}'|awk -F'"' '{print $2}' > /etc/cloudy/${GH_USER}-${GH_REPO}.sha
